language: node_js
node_js:
- 8.11.1
before_deploy: "npm run build"
deploy:
  provider: firebase
  project: proto-notes
  skip_cleanup: true
  token:
    secure: ZNVgFDSnR+YHU1Km1aABOHtZR+l+ViCFMB5Y5WINrCvnNVbkRxGAZ2h09sa7z04QMTXAToq3Pk4/m9xl3lHb/PppSY3he/415xmbDpTBNhEpqJcP3Tna89AVUbxJLqry7s3OoPvpuDiI6neE89jNVvwbx1eLUz0yGytYk7toKyhZ4TuGPjepl7QDO/7R77utsgSfF+zQN9FnhCJIemSNtUGXPqa6Qn4Doeqx3fL7dkbMK26TDrJHgyU3ZOu25UFdeLa3UR3VQWvILCw/Kjq3XyRnhKUjBnqEX283eXd5/+t9G+H1XNs64H15zBvOF6TlOD5E4msK8AglG47Jq/vcIRk7i6inBkMD0hiWHxSG6UV3JXJQBbnItdvQ4yD+AV2lgO+9wper9S6uOmHtDGjA0I3P74z8kR8rpxEByBnOJv66RuCldYG51AUNGv2XZTmtE9Y76C3I72iUCvMy/EPbh6+WotrEg6IIX51rQOnTEZ+Tdl9w/yaQJ9VJpRW3zj8MFHydEd+vlNli7Aa72OGTUlzYG/iUxlHwZC8InG+j55Wu5rkmGXQ1NlTERDxWzTQ0tXHu6CFF1uC6WYYX0rIvnTh9nuMCWpf1POb0HGPBEFriX5rCDIRvR3Xs5QbFg0dXSAan0DR9UfcfohE456nUqHQAb2HWaL3+MPfwaav2U2s=
